[package]
name = "acer_monitor_gui"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.27"
egui = "0.27"

[target.'cfg(target_os = "linux")'.dependencies]
ddc = "0.2"
ddc-i2c = { version = "0.2.2", features = ["i2c-linux"] }

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
